### ISSUE TITLE
Edit 'frontend-container/src/assets/img/tinified/Logo.png:Zone.Identifier' to allow clone

### ISSUE THREAD

**Issue by jbassie** [zepor/NFLSTATS#19]
This is casuing major issues with the clone, so i'm trying to edit this file inorder to allow clone to te possible

**Comment by zepor** [comment]
anything with Zone.Identifier is something i copied from windows over to WSL(Ubuntu). Its just windows metadata basically. Delete anything you see with Zone.Identifier

**Comment by jbassie** [comment]
Please approve PR

**Comment by zepor** [comment]
done
